Develop
OlyaKorolko/request-processing pull request #1
Opened 2020-10-02 16:26 UTC by OlyaKorolko

2020-10-03 15:40 UTC, VeronikaYastr requested changes
Если что-то непонятно в моих комментариях, то ты пиши к ним, что не ясно и я или поясню или сделаю в отдельной ветке пример того, что я имею в виду)

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/StructureHolder.java
> +public class StructureHolder {
Лучше, конечно, назвать его просто Company)
Это же класс-модель компании

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/StructureHolder.java
> +    private final long numberOfEmployees;
Думаю, что int здесь больше подойдет. Зачем выделять много памяти под long

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +            } catch (IOException ex) {
а почему не добавить просто catch(IOException ex) {} перед catch (Exception ex) {} в конце try(), который со сканером?
Просто создавать try() внутри try() это как-то бессмысленно...)

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +            if (processor != null) {
Ну и соответственно тебе тогда не придется делать проверки на null.

Я так понимаю, смысл был в том, чтобы выводить разные сообщения для разных ошибок IOException?

Если да, то можно было бы просто выводить сообщение этого исключения. По идее оно и так будет отличаться в разных случаях.

Либо, что вообще было бы хорошо ,можно создать свое исключение (вот статья об этом https://www.codeflow.site/ru/article/java-new-custom-exception). Это несложно, просто маленький класс с конструкторами) Тогда ты сможешь сделать catch для него конкретный и создать его со своим текстом

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +            System.out.println(ex.getMessage());
Тут тоже хорошо бы вызвать метод processException(). Пусть тоже в файл запишется

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +        holders = null;
А почему нельзя пустой список вместо null?
Тогда по идее если файл пустой и там нет этих компаний, то ничего не упадет, просто на запросы будет возвращаться пустые ответы.

Ну или можно обработать отдельно случай в мэйне типа holders.isEmpty(). В любом случае пустой список это лучше чем null

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +    private final static Logger LOGGER = Logger.getLogger(Processor.class.getName());
Не очень хорошо, что у тебя в этом классе явный вызов класса Processor.
Получается, что если я захочу его использовать где-то еще, то не смогу.

Можно через конструктор передавать название класса и передавать в Logger.getLogger(className);

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +        FileHandler filehandler = new FileHandler(fileName.getName(), true);
Я бы на всякий случай добавила проверку, что file != null. А то на file.getName() в таком случае вылетит ошибка

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +    public void writeRequestDataToLogFile(int requestNum, String input, int result) {
Не совсем очевидные названия параметров

Мб что-то вроде (int requestType, String requestParams/requestInput, int result)?

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +            }
Обычно еще добавляют случай default:

default: {
    LOGGER.fine("Invalid request.");
}

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +        LOGGER.warning(s + "\n");
Исключение это уже не warning, это уже error по идее)

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +            File logFile = Processor.createFile(args[0]);
Аргументы могут быть и пустые. Поэтому лучше добавить проверку if (args.size >= 3)

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +    public static File createFile(String fileName) {
Мб createOutputFile()?
А то не совсем понятно, какой файл создается)

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +            return new StructureHolder(x[0], x[1], LocalDate.parse(x[2]), x[3], LocalDate.parse(x[4]),
Вот лучше здесь написать try {} catch {} и выбрасывать новое исключение, если произошла ошибка при парсинге даты.
А в мэйне уже ее отлавливать и выводить сообщение

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +    private static final int SHORT_NAME = 1;
Чтобы не создавать константы можно создать enum (https://metanit.com/java/tutorial/3.8.php)

Тогда можно будет везде передавать вместо int этот enum (и в логере тоже)

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +        Hashtable<String, StructureHolder> hashTableOfShortName = new Hashtable<>();
Обычно используют HashMap)

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
Почему бы не создать hashTableOfShortname как поле класса и не сохранить туда весь список изначально в конструкторе?
Тогда при вызове запроса shortName у тебя уже будет таблица и ты просто будешь по имени выбирать

2020-10-03 15:40 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
Я все же думаю, стоило сделать так:
в мэйне идет считывание с консоли всех параметров для запросов и потом передаются в processor.searchByName или processor.searchByDate и т.д

То есть в main перенести вот тот switch-case из процессора и в каждом кейсе считывать то, что нужно, потом вызывая метод из процессора. А этот метод пусть возвращает результат просто, который ты потом будешь записывать куда тебе нужно.

2020-10-03 16:05 UTC, OlyaKorolko commented on src/Main/java/com/convertation/StructureHolder.java
> +public class StructureHolder {
ну а какая разница?) это название показывает хотя бы что в классе структура какой то модели)

2020-10-03 16:08 UTC, OlyaKorolko commented on src/Main/java/com/convertation/StructureHolder.java
> +    private final long numberOfEmployees;
ну если пользователь введет какое то большое число то все сломается)
ну вернее исключение выпадет, а вдруг в компании очень много людей) ну прям оооочень много

2020-10-03 17:49 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +            System.out.println(ex.getMessage());
записать в несуществующий файл ошибку о том что этого файла не существует?)

2020-10-03 17:55 UTC, VeronikaYastr commented on src/Main/java/com/convertation/StructureHolder.java
> +public class StructureHolder {
Тогда можно назвать CompanyStructure/CompanyModel/CompanyStructureHolder
Если тебе нужно было бы считывать из 3 разных файлов 3 разных объекта, как бы назывались они тогда?)
StructureHolder1, StructureHolder2, StructureHolder3?🙂

2020-10-03 17:56 UTC, VeronikaYastr commented on src/Main/java/com/convertation/StructureHolder.java
> +    private final long numberOfEmployees;
Больше 2147483647?)
Нормальная такая компания))

Тогда в любой задаче люди бы использовали только long, мало ли что введут)
Нет смысла выделять много памяти под заведомо маловероятный сценарий.

2020-10-03 17:57 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +            System.out.println(ex.getMessage());
А, сори, не заметила, что там у тебя файл может и не создаться. Тогда да, все ок)

2020-10-03 18:07 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +    public static File createFile(String fileName) {
создается и файл ввода, и вывода, так что по сути любой абсолютно

2020-10-03 18:12 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +    public static File createFile(String fileName) {
а, тогда норм

2020-10-03 18:46 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
сохранить весь список нельзя потому что ко времени вызова конструктора он еще пустой

2020-10-03 18:47 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
а вот когда вызывается функция processrequest()- уже заполненный

2020-10-03 18:50 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
Тогда можно в конструкторе пустую hashMap, а потом в setHolders() добавлять и в список, и в map

А вообще не получится использовать только hashMap? Убрать весь этот список и просто хранить все в мапке сразу?

2020-10-03 19:08 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
ну а как потом в мэпе искать в заданных пределах?

2020-10-03 19:10 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
ну это выглядит как минимум некрасиво, 9 циклов все таки) а вообще, я создала процессор именно для того чтобы скрыть огромный свич, так зачем его наружу доставать? разве пользователю нужно видеть то как реализован свич? или это прям важно

2020-10-03 19:11 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
Ну либо брать map.values() (список твоих компаний) и остальной код такой же, как и был
либо просто пройтись по мапке обычным for циклом так же как и по списку

for (Map.Entry<String, StructureHolder> entry : structureHoldersMap) {
}

2020-10-03 19:15 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
так а в чем тогда смысл мэпа?) я создавала его чтобы за константу искать в первом запросе)

2020-10-03 19:16 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
Ну в том, что тебе не нужно будет хранить и список, и мэп. Получается если я буду запрос поиска по имени вызывать 10 раз подряд, каждый раз будет мэп создаваться, хотя данные о компаниях не меняются

2020-10-03 19:17 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
А если мэп хранится как поле класса и меняется только при вызове set метода или add() какого-нибудь, то это более логично и памяти меньше занимает

2020-10-03 19:21 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
почему 9 циклов? Один цикл while() как и в процессоре сейчас

Ну пользователь как бы не видит код)) ни в мэйне, ни в processor-е)

Важно не то, кто что видит, а то, что работа с консолью происходит внутри какого-то класса другого. Обычно ввод-вывод в консоль в мэйне все же, а остальные классы уже в помощь и там что-то возвращают например.

Это не принципиально, можно и так оставить. И кстати, зачем в processRequest передавать processor.getHolders()? Ведь в самом процессоре хранится этот список, почему бы его в методе тогда не вызвать просто?

2020-10-03 19:29 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
имелось ввиду 5 отступов слева, код и так очень сдвинут, а тут еще 3-4 из той функции. но я поняла, что надо ввод в мэйне)

2020-10-03 19:31 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
Да отступы не влияют ни на что, какая разница)
я имела в виду вынести всю функцию в отдельную фукнцию в мэйне

не прямо в метод main() копировать. а сделать там process() {} и его уже вызвать в мэйне)

2020-10-03 19:47 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
ну тогда придется все методы в процессоре сделать публичными. это будет иметь смысл?

2020-10-03 19:48 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
хотя вероятно так и надо было делать. потому что processrequest() использует все из процессора

2020-10-03 19:50 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +                        processor.processRequest(processor.getHolders(), scan, out);
private List<StructureHolder> searchByBranchOrTypeOfWork - вот эти методы можно сделать или публичными, или без модификатора оставить (тогда будут доступны только в пределах пакета). Эти методы ведь по факту и есть смысл этого класса, они и должны быть доступны)
всякие там внутренние штуки только приватные должны быть

2020-10-03 19:59 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
не будет каждый раз мэп создаваться, он будет перезаполняться каждый раз. вообще, нет метода конвертации из потока в хэш мэп, есть только в мэп и список, так что не знаю даже

2020-10-03 20:01 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
вообще тогда нужно будет создавать 5 хэшмэпов на каждый запрос, нехорошо как то

2020-10-03 20:25 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
https://gist.github.com/VeronikaYastr/b5d0bf6ffbd32336ca08a7f8005ff29f

вот, создала пример того, что я имею в виду

2020-10-03 21:36 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Processor.java
> +                    putIntoHashTable(holders, hashTableOfShortName);
о, спасибо большое, не знала что можно писать map<>=new hashmap<>()

2020-10-03 21:54 UTC, VeronikaYastr commented
В целом по-моему стало выглядеть намного лучше и читабельнее💪👍
С try-catch только надо разобраться, чтобы их не было разных в разных участках кода. И чтобы исключения обрабатывались в нужных местах, а не отлавливались где-то ещё. Ну я там писала

И с enum для типа запроса было бы вообще оч красиво)

2020-10-04 09:39 UTC, OlyaKorolko commented
так, а я могу писать блок try catch в processrequest(), например, а в нем уже выбрасывать кастомное исключение? иначе просто не получится, потому что у меня вызов этой функции в мэйне совпадает с открытием файла для записи, а там тоже ioexception

2020-10-04 09:55 UTC, VeronikaYastr commented
Я не совсем понимаю, зачем нужны отдельные try-catch в обработке запросов?
Какие там вообще исключения будут, который не попадают в IOException с фразой "output file is corrupted"?

2020-10-04 09:58 UTC, OlyaKorolko commented
парсинг даты и когда вводят не число на запрос количества работников

2020-10-04 09:59 UTC, OlyaKorolko commented
их в мэйн?

2020-10-04 10:32 UTC, VeronikaYastr requested changes
Я сделала пример с исключениями в отдельной ветке, но у меня нет прав чтобы запушить в твой репозиторий. чтобы я могла это сделать, нужно зайти в твоем репозитории в
settings -> manage access -> invite collaborator и там VeronikaYastr добавить)

2020-10-04 10:32 UTC, VeronikaYastr commented on src/Main/java/com/convertation/CompanyStructure.java
> +    private final Integer numberOfEmployees;
Здесь по идее должно быть просто int numberOfEmployees. Зачем Integer?

2020-10-04 10:32 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +            throw new CustomException("Log file is corrupted.", ex);
Ты видимо не залила CustomException на гитхаб, поэтому я когда скачала репозиторий, у меня его не находит)

2020-10-04 10:32 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +                LOGGER.fine("Find companies by foundation date | date: " +
Проверку надо бы добавить, что в твоем массиве in 2 элемента

2020-10-04 10:32 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +                LOGGER.fine("Find companies by employees number | number: " + "[" + Integer.parseInt(in[0]) +
тут тоже проверка на количество элементов в in и parseInt() может упасть, если передать туда что-то не то...

2020-10-04 10:32 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Processor.java
> +    private Scanner scan;
это поле нигде не используется, можно его убрать

2020-10-04 10:34 UTC, OlyaKorolko commented on src/Main/java/com/convertation/LoggerToFile.java
> +            throw new CustomException("Log file is corrupted.", ex);
да, точно, забыла

2020-10-04 11:28 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
Мне кажется, должно было быть 
String[] in = requestInput.split(" ");
if (in.size == 2) {} else {LOGGER.warning("Unexpected input");}

2020-10-04 11:34 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +            throw new CustomException("Log file is corrupted.", ex);
Конструкторы исключения нужно поправить. В эту ветку добавила примерно, как я вижу обработку исключений. Там не супер идеально, сама идея просто думаю понятна будет. И там же исключение создала с правиьлными конструкторами. 

https://github.com/OlyaKorolko/request-processing/tree/example-branch/src/Main/java/com/convertation

2020-10-04 11:37 UTC, OlyaKorolko commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
до этого уже не дойдет, там есть обработка исключения на стадии парсинга в инт, а иначе ну никак невозможно ввести не 2 элемента

2020-10-04 11:37 UTC, OlyaKorolko commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
записывается request is invalid

2020-10-04 11:39 UTC, OlyaKorolko commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
а как разрешить изменения?)

2020-10-04 11:41 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
> до этого уже не дойдет, там есть обработка исключения на стадии парсинга в инт, а иначе ну никак невозможно ввести не 2 элемента

Ну блин, серьезно?)) А если я сейчас создам класс отдельный, в нем вызову этот метод и передам пустую строку? Каждый метод рассматривается вне зависимости от того, где он там вызывается. Я могу его вызвать откуда угодно с любыми параметрами и он не должен упасть

2020-10-04 11:42 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
Какие изменения? Я залила в веточку example-branch

2020-10-04 11:49 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
Я в целом не понимаю, если ты ожидаешь на вход две даты, то у тебя строка будет состоять из двух слов, но не из двух символов) просто input.length == 2 - это не проверка на то, что там два слова, а проверка, что в строке два символа🤷‍♀️

2020-10-04 12:00 UTC, OlyaKorolko commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
case DATE: {
                String[] in = requestInput.split(" ");
                if (in.length == 2) {
                    LOGGER.fine("Find companies by foundation date | date: " +
                            in[0] + in[1] + ", companies found: " + result + "\n");
                } else {
                    LOGGER.warning("Unexpected input");
                }
                break;
            }
ну вот так получается?

2020-10-04 12:03 UTC, VeronikaYastr commented on src/Main/java/com/convertation/LoggerToFile.java
> +                if (requestInput.length() == 2) {
Да) я так и писала
Ну и для номеров работников тоже так

2020-10-04 21:45 UTC, OlyaKorolko commented
ну вот я вроде как исправила, но теперь получается что дефолт в свиче никогда не будет достигаться. может его убрать? ну и на inputmismatchexception пишется null. не очень как то, может еще один кэтч для него сделать?

2020-10-05 14:47 UTC, VeronikaYastr requested changes

2020-10-05 14:47 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +            rName = RequestName.values()[requestNum - 1];
Обычно если хотят проверить границы массива, то делают просто проверку типа if (requestNum < RequestName.values().length) {}, а не отлавливают исключение)

А вообще лучше в самом RequestName сделать метод:

public static RequestName fromIntValue(int value) {
      for (RequestName name : values()) {
        if (name.number == value) {
          return name;
        }
      }
      return RequestName.DEFAULT;
    }

Тогда он точно не будет падать на неверных значениях

2020-10-05 14:47 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +            } catch (CustomException | IOException | InputMismatchException e) {
Да, если тут некорректно как-то обрабатывается исключение, то ты можешь сделать для него отдельный catch

2020-10-05 14:47 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +                scan.nextLine();
А зачем везде два раза вызывается scan.nextLine()?

2020-10-05 14:51 UTC, VeronikaYastr commented
> ну вот я вроде как исправила, но теперь получается что дефолт в свиче никогда не будет достигаться. может его убрать? 

Аналогично тому что я писала) Если я вызову где-нибудь в другом классе этот метод с числом 10, то без default он упадет.

В твоем случае exit и default в принципе можно обработать одинаково:
case EXIT:
default: {
                LOGGER.fine(requestInput + "\n");
                break;
            }
          
case можно объединять в одну группу с одинаковым кодом:

```
case 1:
case 2:
case 3:
    System.out.println("Number 1-3");
    break;
default:
   System.out.println("Not 1-3 number");
    break;

```

2020-10-07 15:25 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +            rName = RequestName.values()[requestNum - 1];
а, понятно, не знала просто как делается проверка и сделала как знаю)

2020-10-07 15:38 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +                scan.nextLine();
а, потому что с чтением строк проблемы, nextLine читает до первого \n, а после вывода sout почему то считает что конец выведенной фразы это начало новой и получается пустая строка, а next() я написать не могу потому что для фразы из 2+ слов оно не работает

2020-10-07 15:39 UTC, OlyaKorolko commented on src/Main/java/com/convertation/Main.java
> +                scan.nextLine();
не знаю что с этим сделать

2020-10-07 17:10 UTC, VeronikaYastr commented on src/Main/java/com/convertation/Main.java
> +                scan.nextLine();
а, странно... оставляй пока так, посмотрю, что не так

2020-10-08 06:42 UTC, merged